### ISSUE TITLE
v3 first alpha release (finish the huge refactor)

### ISSUE THREAD

**Issue by sophiedeziel** [remcoder/gcode-preview#221]
This issue is to track what's done and what's in flight to have a first alpha release of v3.

Keeping this issue up to date will help in listing out the breaking changes for the migration documentation

The temporary v3.x branch should be merged in develop as soon as it is in a releasable state:
Diff of v3.x with develop: https://github.com/remcoder/gcode-preview/pull/225

# Todo
## MVP to merge the `v3.x` branch on `develop`
- [x] Refactor to introduce new primitives https://github.com/remcoder/gcode-preview/pull/211
  - [x] More performant indexing paths for rendering https://github.com/remcoder/gcode-preview/pull/220
    - [x] Bring back the layer split tolerance https://github.com/remcoder/gcode-preview/pull/224
  - [x] bring back min/max/single layer support https://github.com/remcoder/gcode-preview/pull/234
  - [x] bring back layer height setting https://github.com/remcoder/gcode-preview/pull/227
  - [x] bring back line width setting https://github.com/remcoder/gcode-preview/pull/227
  - [x] bring back renderExtrusion and renderTubes https://github.com/remcoder/gcode-preview/pull/228
  - [x] Remove the Code enum https://github.com/remcoder/gcode-preview/pull/229
  - [x] Bring back the layer class https://github.com/remcoder/gcode-preview/pull/233

## New features
- [x] Implement G21 https://github.com/remcoder/gcode-preview/pull/218
- [x] Implement G28 https://github.com/remcoder/gcode-preview/pull/219

# Breaking changes
- Layers are accessible via `preview.job.layers` instead of `preview.layers`. It returns `Path[][]` instead of `Layer[]`
- `preview.currentToolColor()` deleted
- ... (list here the deletion of deprecated methods/attributes)
